### ISSUE TITLE
Remote upload 

### ISSUE THREAD

**Issue by chetankatke** [tanaikech/Resumable_Upload_For_WebApps#2]
Is it possible to upload file from url by using this script

**Comment by tanaikech** [comment]
This script cannot directly upload a file from an URL. I apologize that this sample is not useful for your situation.

**Comment by tanaikech** [comment]
I remembered just now. Is this useful for your situation?
[https://github.com/tanaikech/DownloadLargeFilesByUrl](https://github.com/tanaikech/DownloadLargeFilesByUrl)
